# Make sure to check the documentation at https://goreleaser.com
version: 2
before:
  hooks:
    - go mod tidy
    - go generate ./...
gomod:
  proxy: true
builds:
  - main: ./cmd/
    env:
      - CGO_ENABLED=0
    id: readium
    binary: readium
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    goarm:
      - '7'
    goamd64:
      - v3
    ldflags:
      - -s -w

archives:
  - formats: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    # Used to start with {{ .ProjectName }}
    name_template: >-
      readium_
      {{- tolower .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      formats: ['zip']
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
