name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ '**' ]

permissions:
  contents: read

jobs:

  build:
    runs-on: [self-hosted, arm64]
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
      with:
        egress-policy: audit

    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: '>=1.24.2'
        cache: false

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
