name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ '**' ]

permissions:
  contents: read

jobs:

  build:
    runs-on: [self-hosted, arm64]
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Go
      uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
      with:
        go-version: '>=1.24.2'
        cache: false

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
